# Generated by Django 5.1.1 on 2024-09-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fii",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
                ("total_amount", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
