# Generated by Django 5.1.1 on 2024-09-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiis", "0002_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="type_trade",
            field=models.CharField(
                choices=[("C", "compra"), ("V", "venda"), ("SUB", "subscrição")],
                default="C",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
