# Generated by Django 5.1.1 on 2024-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiis", "0003_trade_type_trade_alter_trade_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiiInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiis_count", models.IntegerField()),
                ("total_amount_invested", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="trade",
            name="type_trade",
            field=models.CharField(
                choices=[("C", "Compra"), ("V", "Venda"), ("SUB", "Subscrição")],
                default="C",
                max_length=3,
            ),
        ),
    ]
