# Generated by Django 5.1.1 on 2024-10-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fiis", "0004_fiiinventory_alter_trade_type_trade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fii",
            name="total_amount",
        ),
    ]
